main: main.cpp Calculator.cpp Calculator.h PerformStrategy.cpp PerformStrategy.h LevelStrategy.cpp LevelStrategy.h
	g++ main.cpp Calculator.cpp PerformStrategy.cpp LevelStrategy.cpp -o main -std=c++14

clean:
	rm main